version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: itrim-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  wordpress:
    image: wordpress:latest
    container_name: itrim-wordpress
    restart: always
    depends_on:
      - db
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./backend/wp-content:/var/www/html/wp-content
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: itrim-phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  nuxt:
    image: node:20
    container_name: itrim-nuxt
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    environment:
      NUXT_PUBLIC_API_URL: ${NUXT_PUBLIC_API_URL}

volumes:
  db_data:
